### ISSUE TITLE
window frames are indestructible

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [RMC-14/RMC-14#3660]
you are only able to deconstruct them or acidify them

**Comment by deltanedas** [comment]
according to window_frame.dm it has 600 health which seems ridiculously high for something you can deconstruct in a second

**Comment by Vermidia** [comment]
They don't flash when damage I think is mostly it. You can destroy them.

**Comment by DummeHytteOst** [comment]
> They don't flash when damaged I think is mostly it. You can destroy them though attacking.

The reason they appear to not take damage sometimes, is because the window frames damage modifer has a flat redution of 10/10/10 blunt/slash/piercing.
 
[Damage modifier](https://github.com/RMC-14/RMC-14/blob/01b3b2578234661624005631b6dcdb70938a0e28/Resources/Prototypes/Damage/modifier_sets.yml#L28)
> - type: damageModifierSet
  id: StructuralMetallic
  coefficients:
    Shock: 1.2
    Heat: 1.2
    Structural: 0.5
  flatReductions:
    Blunt: 10
    Slash: 10
    Piercing: 10
    Heat: 10
    Structural: 10

now, the reason this matters is because xenos deal brute damage, which is a group of damage types, brute consists of blunt, slash and piercing, so when you deal lets say 15 brute, then it is split equally to each of the damage types in the brute group, so 5/5/5 blunt/slash/piercing, meaning you need to do >30 brute to deal damage to a window frame, currently there is only 4 xenos who can damage window frames with their base attack, without frenzy.

### Final damage 0

1. **Drone**: 22.5 brute
2. **HiveLord**: 22.5 brute
3. **Defender**: 27.5 brute
4. **and every other xenonid currently**

### Final damage 5, total hits to destroy a window frame: 120

1. **Warrior**: 35 brute
2. **Lurker**: 35 brute

### Final damage 10, total hits to destroy a window frame: 60

1. **Queen**: 40 brute
2. **Crusher**: 40 brute


i don't know how much damage they could take in CM13, but it seems way too high currently, the modifier is from upstream wizden, which is likely why it isn't balanced for this fork

**Comment by Vermidia** [comment]
Ahh that makes sense

**Comment by DummeHytteOst** [comment]
>Final damage 5, total hits to destroy a window frame: 120
>Warrior: 35 brute
>Lurker: 35 brute
>Final damage 10, total hits to destroy a window frame: 60
>Queen: 40 brute
>Crusher: 40 brute
>
this does also mean that a [boilers spit](https://github.com/RMC-14/RMC-14/blob/01b3b2578234661624005631b6dcdb70938a0e28/Resources/Prototypes/_RMC14/Actions/Xeno/xeno_offense_actions.yml#L37) is actually a lot faster, since it takes 60 seconds to melt, and a lone warrior will take at least 2 minutes.

> event: !type:XenoCorrosiveAcidEvent
      acidId: XenoAcidStrong
      plasmaCost: 125
      time: 60

and [normal acid](https://github.com/RMC-14/RMC-14/blob/01b3b2578234661624005631b6dcdb70938a0e28/Resources/Prototypes/_RMC14/Actions/Xeno/xeno_offense_actions.yml#L3) is slightly faster than a lone lurker, a lurker will take at least 2m40s, due to lower attack speed being a thing, and the normal acid takes 2m30s to melt

> event: !type:XenoCorrosiveAcidEvent
      acidId: XenoAcidNormal
      plasmaCost: 100
      time: 150

**Comment by Vermidia** [comment]
There's probably rmc versions for these, I'll look into fixing it

**Comment by Vermidia** [comment]
Nvm, only aliens with claw type sharp and very sharp can destroy them in CM-13.
This happens to apply to warrior, lurker, queen, crusher (and some strains of praetorian).
The actual hits to destroy is off but that's something to look at later. (Like crusher two hits it in CM-13)
