### ISSUE TITLE
Holding Armour in your hand applies no movement speed penalty

### ISSUE THREAD

**Issue by EpicJoston** [RMC-14/RMC-14#3693]
## Description
On upstream a movement speed penalty for hardsuits is applied if you are holding them as well as if you are wearing them. In RMC, simply holding the armour has no effect on movement speed.

**Reproduction**
Hold armour in your hand, experience mobility as if you were armourless.

**Comment by Siigiil** [comment]
Intended.

**Comment by QuietlyWhisper** [comment]
oops

**Comment by EpicJoston** [comment]
Good to know this is intended :)

**Comment by Rainbeon** [comment]
> Good to know this is intended :)

As an additional balance comment for why this is okay vs upstream's, on upstream you put on/take off hardsuits instantly which is why the slow-in-hand thing was introduced, there was no downside to doing it for traveling. Here you have to sit completely still and go through a fairly long do-after to swap on/off armor, meaning it adds a fair amount of travel time due to having to stop at the start and end + you won't be combat ready by the time you get where you were going
