### ISSUE TITLE
RMC14 -  Stop motion film update

### ISSUE THREAD

**Issue by ARMOKS** [RMC-14/RMC-14#3801]
Round 872 turned into a stop motion film, everyone had 3~ FPS, all walls were gone, and everyone was naked. No clue what caused it but it was tragic and headache inducing. Server was restarted to fix it.

**Comment by Aurallianz** [comment]
pvs issue

**Comment by DrSmugleaf** [comment]
We finally figured out the cause and a workaround, the issue is that if at round-end entities fail to be deleted due to an error or anything else, the next round's PVS data can get corrupted
Ironically diagnosing this issue solved it with a workaround, as the server now throws another error when this happens, which makes the PVS data stay in sync
The PR that changed the engine version to diagnose this was https://github.com/RMC-14/RMC-14/pull/3886, which we will stay on until this is fixed properly
